require("dotenv").config();
module.exports = {
	PORT: process.env.PORT,
	DB_AUTH_URL: process.env.DB_AUTH_URL,
	SERVERERROR: 500,
	UNAUTHORIZED: 401,
	SUCCESS: 200,
	FAILURE: 400,
	NO_CONTENT: 404,
	ACTIVE: true,
	INACTIVE: false,
	DELETED_STATUS: 3,
	JWT_AUTH_TOKEN_SECRET: "infytabscare",
	CRYPTO_SECRET: "infytabscare",
	JWT_EXPIRES_IN: "365d",
	RESET_TOKEN_EXPIRES: "20m",
	PAGINATION_LIMIT: 10,
	META_STATUS_0: 0,
	META_STATUS_1: 1,
	APP_URL: process.env.APP_URL,
	APP_WEB_LINK : "link",
	HOST: "localhost",
	USER: 'root',
	PASSWORD: '',
	DB: 'mymeeting',
	dialect: 'mysql',
	pool: {
	  max: 5,
	  min: 0,
	  acquire: 30000,
	  idle: 10000
	},
	TEMPLATE_ID : process.env.TEMPLATE_ID,
	AUTH_KEY : process.env.AUTH_KEY,
	FLOW_ID : process.env.FLOW_ID,
	SENDER_ID: process.env.SENDER_ID,
	COUNTRY_CODE : '+91',
	STRIPE_KEY: process.env.STRIPE_KEY,
	TWILIO_ACCOUNT_SID : process.env.TWILIO_ACCOUNT_SID,
	TWILIO_AUTH_TOKEN : process.env.TWILIO_AUTH_TOKEN,
	TWILIO_LOG_LEVEL : process.env.TWILIO_LOG_LEVEL,
	TWILIO_STATUS_CALLBACK_URL : process.env.TWILIO_STATUS_CALLBACK_URL,
	TWILIO_KEY : process.env.TWILIO_KEY,
	TWILIO_SECRET : process.env.TWILIO_SECRET,
	FCM_VENDOR_APP_KEY : process.env.FCM_VENDOR_APP_KEY,
	FCM_CLIENT_APP_KEY : process.env.FCM_CLIENT_APP_KEY,
};
